### ISSUE TITLE
Missing validation split files

### ISSUE THREAD

**Issue by isaaccorley** [schmitt-muc/SEN12MS#3]
@schmitt-muc Just want to start off with saying I appreciate the effort made to create a multimodal dataset like this.

I am trying to use the dataset from the SEN12MS/classification/dataloader.py script, however it seems that a val_list.pkl and val_list.txt file is missing from the SEN12MS/splits directory. Any chance that this could be uploaded? Thanks!

**Comment by schmitt-muc** [comment]
@isaaccorley And I appreciate your interest in the dataset and repository. :)

You are correct, we have not provided a validation file list, as there are different strategies to define a good val set. Thus, we decided to leave it to the users. 

I would suggest the following procedure: 
- Decide how large you want your val set to be, i.e. how many patches it should contain
- Sample (randomly) those patches from the "training" split, i.e. from those patches that are not part of the hold-out split provided by us. 
- Remove the selected validation patches from the training set list. 

Hope that helps!

**Comment by isaaccorley** [comment]
@schmitt-muc This definitely helps. Thanks for the insight.
