### ISSUE TITLE
False color Sentinel-1 SAR code example

### ISSUE THREAD

**Issue by hjinnkim** [schmitt-muc/SEN12MS#7]
Hello, everyone.
I really appreciate for your great detailed dataset and utils. 
Actually, I'm pretty new for this area, so having trouble with pre-processing Sentinel-1/2 dataset.

Above all, I want to visualize Sentinel-1 as Figure 4 in your paper (False color Sentinel-1 SAR), but I'm failed to reproduce them.

Can you provide example code for visualizing "False color Sentinel-1 SAR" or any reference materials for it?

Thank your advance!

**Comment by schmitt-muc** [comment]
Hello hjinnkim,
as the caption says,  these false color Sentinel-1 SAR images display the VV backscatter in the red channel, the VH backscatter in the green channel, and the ratio of VV and VH in the blue channel. The most important point for the visualization is the scaling: In it's original form, Sentinel-1 backscatter is provided in dB scale, i.e. it contains floating point numbers ranging from about -30 or so to about 0 or so. The VV/VH ratio naturally will be a dimensionless number around 1. If you put those numbers into the three color channels without further preprocessing, nothing useful will show up. It depends on the type of library you use for visualization or the type of image you seek to create, but typically you will have to rescale the three values (VV, VH, VV/VH) to the range [0;1] (double precision) or [0;255] (integers).

**Comment by hjinnkim** [comment]
@schmitt-muc 

Thank you for your reply!

Based on your suggestion, I successfully visualize False Color SAR. Thank you!
